# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Kling-Gupta Efficiency
#'
#' @description Kling-Gupta efficiency function
#'
#' @param x numeric vector
#' @param y numeric vector of same length as x
#' 
#' @return KGE value
#'
.KGE2011cpp <- function(x, y) {
    .Call(`_ccrits_KGE2011cpp`, x, y)
}

#' Nash-Sutcliffe Efficiency
#'
#' @description Nash-Sutcliffe Efficiency wrapper function
#'
#' @param x numeric vector of observed values
#' @param y numeric vector of simulated values
#' 
#' @return NSE value
#'
.NSEcpp <- function(x, y) {
    .Call(`_ccrits_NSEcpp`, x, y)
}

#' Liu Mean Efficiency
#'
#' @description Liu Mean Efficiency wrapper function. This criteria aims to \deqn{\text{LME} = 1 - \sqrt{(k_1 - 1)^2 + (\beta - 1)^2}}
#' 
#' 
#'
#' @param x numeric vector of observed values
#' @param y numeric vector of simulated values
#' 
#' @return LME value
#'
.LMEcpp <- function(x, y) {
    .Call(`_ccrits_LMEcpp`, x, y)
}

rcpp_hello_world <- function() {
    .Call(`_ccrits_rcpp_hello_world`)
}

